import type { Locale } from "./i18n"
const en = {
  shop: "Service parts",
  account: "My account",
  cart: "Cart",
  search: "Search parts",
  placeholder: "Search by part name or number…",
  categories: "Categories",
  allCategories: "All parts",
  machine: "Your machine",
  allMachines: "All machines",
  stockOnly: "In stock only",
  filters: "Filters",
  sort: "Sort by",
  relevance: "Recommended",
  priceAsc: "Price: low to high",
  priceDesc: "Price: high to low",
  name: "Name: A–Z",
  results: "parts",
  clear: "Clear filters",
  noResults: "No matching parts.",
  noResultsText: "Try a shorter name, a part number or a different machine.",
  inStock: "In stock",
  unavailable: "Out of stock",
  add: "Add to cart",
  added: "Added to cart",
  viewCart: "View cart",
  tax: "Excl. VAT",
  taxDelivery: "Prices exclude VAT and delivery.",
  compatible: "Fits",
  partNumber: "Part number",
  details: "About this part",
  quantity: "Quantity",
  maxQuantity: "Maximum available quantity reached",
  related: "A little care goes a long way.",
  relatedText:
    "Find the checks and maintenance steps that keep your machine ready.",
  readGuide: "Open maintenance guide",
  back: "Back to parts",
  continue: "Continue shopping",
  emptyCart: "Your cart is ready for the next job.",
  emptyCartText: "Find the parts you need and add them here.",
  remove: "Remove",
  subtotal: "Parts subtotal",
  summary: "Order summary",
  checkout: "Continue to order",
  deliveryLabel: "Delivery",
  deliveryQuote: "Calculated with your order",
  vat: "VAT",
  vatQuote: "Calculated for your delivery address",
  payment: "Payment",
  paymentText:
    "Payment is arranged separately after the parts and delivery are agreed.",
  request: "Save order request",
  checkoutTitle: "Ready for the next job.",
  checkoutIntro: "Add your details and review the parts in your request.",
  contact: "Your details",
  deliveryAddress: "Delivery address",
  fullName: "Full name",
  email: "Email",
  phone: "Phone (optional)",
  company: "Company (optional)",
  address: "Street address",
  postalCode: "Postal code",
  city: "Town / city",
  country: "Country",
  selectCountry: "Choose country",
  optional: "Optional",
  machineDetails: "Your machine",
  model: "Machine model",
  serial: "Machine serial number (optional)",
  machineHint: "A serial number helps identify the right fit for your machine.",
  saveDetails: "Save my details for next time",
  deliveryMethod: "How would you like your parts?",
  deliveryOption: "Deliver to my address",
  collection: "Collect in Tuusula",
  collectionText: "Piikivenkuja 3, 04300 Tuusula, Finland",
  notes: "Anything else? (optional)",
  notesPlaceholder: "Engine reference, mounting position or delivery notes…",
  saved: "Your order request is saved.",
  savedText: "Your parts and contact details are gathered below.",
  reference: "Request reference",
  download: "Download request",
  savedRequests: "Saved requests",
  noOrders: "Your saved requests will appear here.",
  profile: "Contact & delivery details",
  accountTitle: "Your next job, a little easier.",
  accountIntro: "Keep your details, machine and parts requests together.",
  saveProfile: "Save details",
  profileSaved: "Your details are saved.",
  repeat: "Add available parts to cart",
  requested: "Saved",
  viewRequest: "View request",
  error:
    "We couldn’t save your changes. Check your browser storage settings and try again.",
  orderMissing: "This request could not be found.",
  orderMissingText:
    "Open a saved request from your account, or start with the parts you need.",
  loaded: "Loading your details…",
  accountLink: "Open my account",
  orderItems: "Your parts",
  decrease: "Decrease quantity",
  increase: "Increase quantity",
  support: "Need help finding a part?",
  supportText:
    "Send us your machine model, serial number and a photo of the part.",
  supportAction: "Ask about a part",
  countryOther: "Another country",
  countryName: "Country name",
  savedState: "Details saved",
  singlePart: "part",
  emptyOrder: "Add a part to your cart to begin.",
  deleteRequest: "Delete request",
  clearProfile: "Clear saved details",
  orderDate: "Saved on",
  itemsAdded: "Available parts added to your cart.",
  matched: "Search results for",
  catalogLoading: "Loading parts…",
}
const fi: Record<keyof typeof en, string> = {
  shop: "Varaosat",
  account: "Oma tili",
  cart: "Ostoskori",
  search: "Etsi varaosia",
  placeholder: "Hae osan nimellä tai numerolla…",
  categories: "Tuoteryhmät",
  allCategories: "Kaikki osat",
  machine: "Oma koneesi",
  allMachines: "Kaikki koneet",
  stockOnly: "Vain varastossa olevat",
  filters: "Suodattimet",
  sort: "Järjestys",
  relevance: "Suositellut",
  priceAsc: "Hinta: halvin ensin",
  priceDesc: "Hinta: kallein ensin",
  name: "Nimi: A–Ö",
  results: "osaa",
  clear: "Tyhjennä rajaukset",
  noResults: "Osia ei löytynyt.",
  noResultsText: "Kokeile lyhyempää nimeä, osanumeroa tai toista konemallia.",
  inStock: "Varastossa",
  unavailable: "Loppu varastosta",
  add: "Lisää koriin",
  added: "Lisätty koriin",
  viewCart: "Näytä ostoskori",
  tax: "Alv 0 %",
  taxDelivery: "Hinnat ilman arvonlisäveroa ja toimitusta.",
  compatible: "Sopivuus",
  partNumber: "Osanumero",
  details: "Tietoa osasta",
  quantity: "Määrä",
  maxQuantity: "Saatavilla oleva enimmäismäärä saavutettu",
  related: "Pienellä huollolla pitkälle.",
  relatedText:
    "Löydä tarkistukset ja huolto-ohjeet, joilla kone pysyy valmiina töihin.",
  readGuide: "Avaa huolto-ohje",
  back: "Takaisin varaosiin",
  continue: "Jatka ostoksia",
  emptyCart: "Ostoskorisi odottaa seuraavaa työtä.",
  emptyCartText: "Löydä tarvitsemasi osat ja lisää ne tänne.",
  remove: "Poista",
  subtotal: "Osat yhteensä",
  summary: "Tilauksen yhteenveto",
  checkout: "Jatka tilaamaan",
  deliveryLabel: "Toimitus",
  deliveryQuote: "Lasketaan tilauksen yhteydessä",
  vat: "Arvonlisävero",
  vatQuote: "Lasketaan toimitusosoitteen mukaan",
  payment: "Maksaminen",
  paymentText:
    "Maksaminen sovitaan erikseen osien ja toimituksen vahvistamisen jälkeen.",
  request: "Tallenna tilauspyyntö",
  checkoutTitle: "Valmiina seuraavaan työhön.",
  checkoutIntro: "Lisää yhteystietosi ja tarkista tilauspyynnön osat.",
  contact: "Yhteystietosi",
  deliveryAddress: "Toimitusosoite",
  fullName: "Koko nimi",
  email: "Sähköposti",
  phone: "Puhelin (valinnainen)",
  company: "Yritys (valinnainen)",
  address: "Katuosoite",
  postalCode: "Postinumero",
  city: "Postitoimipaikka",
  country: "Maa",
  selectCountry: "Valitse maa",
  optional: "Valinnainen",
  machineDetails: "Oma koneesi",
  model: "Konemalli",
  serial: "Koneen sarjanumero (valinnainen)",
  machineHint: "Sarjanumero auttaa tunnistamaan koneeseesi sopivat osat.",
  saveDetails: "Tallenna tietoni seuraavaa kertaa varten",
  deliveryMethod: "Miten haluat osasi?",
  deliveryOption: "Toimitus osoitteeseeni",
  collection: "Nouto Tuusulasta",
  collectionText: "Piikivenkuja 3, 04300 Tuusula",
  notes: "Muuta huomioitavaa? (valinnainen)",
  notesPlaceholder: "Moottorin viitenumero, asennuspaikka tai toimitusohjeita…",
  saved: "Tilauspyyntösi on tallennettu.",
  savedText: "Osat ja yhteystietosi on koottu alle.",
  reference: "Pyynnön viite",
  download: "Lataa tilauspyyntö",
  savedRequests: "Tallennetut pyynnöt",
  noOrders: "Tallentamasi tilauspyynnöt näkyvät täällä.",
  profile: "Yhteys- ja toimitustiedot",
  accountTitle: "Seuraava työ, hieman helpommin.",
  accountIntro: "Pidä yhteystiedot, kone ja osatilaukset yhdessä paikassa.",
  saveProfile: "Tallenna tiedot",
  profileSaved: "Tietosi on tallennettu.",
  repeat: "Lisää saatavilla olevat osat koriin",
  requested: "Tallennettu",
  viewRequest: "Näytä pyyntö",
  error:
    "Muutosten tallentaminen ei onnistunut. Tarkista selaimen tallennusasetukset ja yritä uudelleen.",
  orderMissing: "Tilauspyyntöä ei löytynyt.",
  orderMissingText:
    "Avaa tallennettu pyyntö omalta tililtäsi tai etsi tarvitsemasi osat.",
  loaded: "Ladataan tietojasi…",
  accountLink: "Avaa oma tili",
  orderItems: "Tilauksen osat",
  decrease: "Vähennä määrää",
  increase: "Lisää määrää",
  support: "Apua oikean osan löytämiseen?",
  supportText: "Lähetä konemalli, sarjanumero ja kuva tarvitsemastasi osasta.",
  supportAction: "Kysy varaosasta",
  countryOther: "Muu maa",
  countryName: "Maan nimi",
  savedState: "Tiedot tallennettu",
  singlePart: "osa",
  emptyOrder: "Lisää osa ostoskoriin aloittaaksesi.",
  deleteRequest: "Poista pyyntö",
  clearProfile: "Tyhjennä tallennetut tiedot",
  orderDate: "Tallennuspäivä",
  itemsAdded: "Saatavilla olevat osat lisätty koriin.",
  matched: "Hakutulokset haulle",
  catalogLoading: "Ladataan osia…",
}
export const partsCopy = (locale: Locale) => (locale === "fi" ? fi : en)
